apiVersion: v1
kind: Namespace
metadata:
  name: --environment--

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: --environment--
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/inglesefe/web:--version--
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: --environment--
  labels:
    app: web
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      nodePort: 31010
  selector:
    app: web
